### PR TITLE
Add some tests for helper functions

### PR DESCRIPTION
**Pull request by DmitrySharabin**
@LeaVerou Could you please have a look? I might have misunderstood how some of the functions should work and some of the tests I wrote might be wrong. Feel free to correct me.

### CODE REVIEW

**Comment by DmitrySharabin** [comment]
Preview: https://deploy-preview-5--ma-vue.netlify.app/functions/test.html

**Review by LeaVerou — CHANGES_REQUESTED** [review]
This looks good, but since we are processing the function calls anyway I was wondering if we could use the 3 column format, so that the function calls are also printed out (i.e. first column contains the function call, second the result, third the expected result).
This would also make the testsuite valuable as a list of examples, and would make it easier to read.

**Comment by LeaVerou** [comment]
Nice catch on the failures too, yikes!

**Comment by DmitrySharabin** [comment]
Luckily, we already have the three column layout. Please have a look. 

https://deploy-preview-5--ma-vue.netlify.app/functions/test.html

Or do I misunderstand something?

**Comment by LeaVerou** [comment]
In fact, I'm gonna merge this so I can work on fixes, I can make the change to the 3 col format

**Comment by LeaVerou** [comment]
...and I just noticed you've already done this 🤦🏽‍♀️ Sorry Dmitry! I'm so overworked these days my brain is turning to mush.

**Comment by LeaVerou** [comment]
We should probably use `tests/index.html` instead of `test.html` so we can move to a testsuite later and keep the same URL (`/tests/`)

**Comment by DmitrySharabin** [comment]
> ...and I just noticed you've already done this 🤦🏽‍♀️ Sorry Dmitry! I'm so overworked these days my brain is turning to mush.

No worries. I totally get it. Please take care of yourself!

**Comment by DmitrySharabin** [comment]
> We should probably use `tests/index.html` instead of `test.html` so we can move to a testsuite later and keep the same URL (`/tests/`)

Agreed. Do you mind me doing this? I don't want to interfere with the work you might be doing now, so feel free to ping me later. Don't want to ruin something with those merge commits. 🙈

**Comment by LeaVerou** [comment]
I've done it already, sorry!

**Comment by LeaVerou** [comment]
It required fixing an htest bug, since htest assumed that if it was running on index.html, it must be the index of tests and not a single set of tests

**Comment by DmitrySharabin** [comment]
Got it. Thanks!

**Pull request merged**
